#!/bin/sh
#
# git-hyperfine: thing wrapper around hyperfine(1). See --help output
# below.

debug=
debug() {
	if test -n "$debug"
	then
		if test $# -gt 0
		then
			prefix=$1
			shift
			printf "debug: $prefix: %s\n" $@
		fi
		return 0
	fi
	return 1
}

# Out option variables
debug_trace=
trace=
dry_run=
worktree_list=
worktree_xargs=

# "Our" option variables
setup=
prepare=
cleanup=
command=
command_name=

# "Our' options variables, intecepted (TODO)
help=
version=

# Pass-through to hyperfine(1)
hyperfine_opt=
hyperfine_output_opt=

# Pass-through to hyperfine(1), but validate
saw_rev=

while test $# -gt 0
do
	debug "getopt: processing" $1
	case "$1" in
	# git-hyperfine's own options
	--ghf-debug)
		debug=t
		;;
	--ghf-debug-trace)
		set -x
		debug_trace=t
		;;
	--ghf-trace)
		trace=t
		;;
	--ghf-dry-run)
		dry_run=t
		;;
	--ghf-worktree-xargs)
		debug "getopt: aborting" $1
		worktree_xargs=t
		shift
		break
		;;
	--ghf-worktree-list)
		debug "getopt: aborting" $1
		worktree_list=t
		shift
		break
		;;
	--ghf-*)
		echo "git-hyperfine: unknown option $1" >&2
		exit 1
		;;
	# I need to explicitly intercept these..
	-s|--setup)
		setup=$2
		shift
		;;
	-p|-prepare)
		prepare=$2
		shift
		;;
	-c|--cleanup)
		cleanup=$2
		shift
		;;
	-n|--command-name)
		command_name=$2
		shift
		;;

	# ... but not really these. TODO: Better way to do passthrough
	# "and" understand <command> than to re-parse every option it
	# understands?
	#
	# Probably not, I'll need to know if -L <x> <y> has <y> as a
	# <command> or argument for -L.
	-P|--parameter-scan)
		# Options for hyperfine(1) with three params
		hyperfine_opt="${hyperfine_opt:+$hyperfine_opt }$1 $2 $3 #4"
		shift 3
		;;
	# Options for hyperfine(1) with two params
	-L|--parameter-list)
		if test "$2" = "rev"
		then
			saw_rev=t
		fi
		hyperfine_opt="${hyperfine_opt:+$hyperfine_opt }$1 $2 $3"
		shift 2
		;;
	# Options for hyperfine(1) with one param.
	-w|--warmup| \
	-m|--min-runs| \
	-M|--max-runs| \
	-r|--runs| \
	--style| \
	-D|--parameter-step-size| \
	-S|--shell| \
	-u|--time-unit| \
	--export-asciidoc| \
	--export-csv| \
	--export-markdown| \
	--export-json)
		hyperfine_opt="${hyperfine_opt:+$hyperfine_opt }$1 $2"
		shift
		;;
	# Options for hyperfine(1) without params
	-i|--ignore-failure| \
	--show-output)
		hyperfine_opt="${hyperfine_opt:+$hyperfine_opt }$1"
		;;
	# Output options for hyperfine(1) without params
	-h|--help)
		help=t
		hyperfine_output_opt="${hyperfine_output_opt:+$hyperfine_output_opt }$1"
		;;
	-v|--version)
		version=t
		hyperfine_output_opt="${hyperfine_output_opt:+$hyperfine_output_opt }$1"
		;;
	*)
		# Intercept hyperfine(1) <command>
		command="${command:+$command }$1"
		;;
	esac
	shift
done

## Options debug
debug "getopt: setup" $setup
debug "getopt: prepare" $prepare
debug "getopt: cleanup" $cleanup
debug "getopt: hyperfine opts" $hyperfine_opt
debug "getopt: hyperfine command" $command
debug "getopt: hyperfine command_name" $command_name

## --help output specific to git-hyperfine
if test -n "$help"
then
	cat <<-\EOF
git-hyperfine(1)
================

NAME
----
git-hyperfine(1) - wrapper around man:hyperfine[1], intercepts -L '<rev>', benchmarks git revisions

SYNOPSIS
--------

[verse]
git hyperfine [<git-hyperfine-options>] -L rev <comma-delimited-git-revisions> [<hyperfine-options>]
git hyperfine [<git-hyperfine-options>] -L rev HEAD~1,HEAD~0 -r 1 pwd
git hyperfine [--ghf-dry-run] --ghf-worktree-xargs [<args>]
git hyperfine --ghf-worktree-list

See more examples under <<XMPL,EXAMPLES>> below.

DESCRIPTION
-----------

git-hyperfine is a thin wrapper around man:hyperfine[1] designed to
make it convenient to benchmark different git revisions within a git
repository.

It '-L rev <git-revisions>' and sets up a git-worktree(1) for each one
under a prefix you configure. Providing '-L rev` is mandatory and will
be used to create the '<path>' fed to 'git worktree add'. We'll then
wrap man:hyperfine[1] so that any commands are run within this newly
setup worktree.

The rest of the usage is the same as man:hyperfine[1] itself, but see
<<OPT,OPTIONS>> and <<ALTOPT,ALTERED OPTIONS>> for extra options on
top, and details about how we intercept and munge certain options.

It needs the --setup option from
https://github.com/sharkdp/hyperfine/pull/448, and some of the
examples here use the recent (as of late 2021) support for '-r 1'.

DISCUSSION
----------

To test say a <git-revisions> of 'HEAD~1,HEAD~0' well resolve those
comma-delimited revisions in the current working directory. You're
assumed to be running this within git repository, if not we'll die.

We'll then expect a 'hyperfine.run-dir' in your git-config(1) of
e.g. (we'll 'eval' it, so you can use an env variable name):

----
[hyperfine]
run-dir = $XDG_RUNTIME_DIR/git-perf
----

Which, on e.g. modern systemd-using system will resolve to a ramdisk
directory such as '/run/user/1001/git-perf'. We'll then create (with
'git worktree add') both of:

----
/run/user/1001/git-perf/HEAD~0
/run/user/1001/git-perf/HEAD~1
----

Note that we use those literal names, i.e. 'HEAD~0', not whatever 'git
rev-parse HEAD~0'. This is so that we won't create an arbitrary number
of directories over multiple runs. We'll expect that you can re-use
them if you keep testing the last N revisions.

OPTIONS[[OPT]]
--------------

All options that 'git-hyperfine' interprets are prefixed with
'--ghf-'. Any other option is passed through to
man:hyperfine[1]. We'll change some of them as noted in
<<ALTOPT,ALTERED OPTIONS>>.

--ghf-dry-run::
	Don't run the man:git-hyperfine[1] command, show what would
	have been run.

--ghf-worktree-list::
	A convenience wrapper, runs man:git-worktree[1] with 'list
	--porcelain' and emits only those paths configured under our
	'hyperfine-run-dir' prefix. Useful for e.g.:
+
----
git hyperfine --ghf-worktree-list | xargs -n 1 git worktree remove
----

--ghf-worktree-xargs::
	A convenience wrapper for piping '--ghf-worktree-list' output
	to man:xargs[1]. Equivalent to:
+
----
git hyperfine --ghf-worktree-list | xargs -n 1 $(git config hyperfine.xargs-options) <your command>
----
+
Use it as e.g.:
+
----
git hyperfine --ghf-worktree-xargs git worktree remove
----
+
To clean up the worktrees which git-hyperfine will create for running
benchmarks.
+
Under '--dry-run' we inject an 'echo' before whatever command it is
you wanted to run.

--ghf-trace::
	Instrument generated code with "set -x". For use with
	man:git-hyperfine[1]'s '--show-output'.

--ghf-debug, --ghf-debug-trace::
	For debugging git-hyperfine itself. '--ghf-debug' shows debug
	output about option parsing etc. The '--ghf-debug-trace' turn
	on 'set -x' for git-hyperfine itself, as opposed to
	'--ghf-trace' which'll only do it for your code.

ALTERED OPTIONS[[altopt]]
-------------------------

<command>:
	In addition to being altered for link:git-worktree[1] use this
	is optional if 'hyperfine.hook.command' is defined. See
	<<HOOKCFG,HOOK CONFIGURATION>>.

--help, --version::
	git-hyperfine's help and version output. The help output is
	the raw asciidoc of the installed man page.

--setup, --prepare, <command>::
	 Your '--setup' command (if any) will be chained behind the
	 setup command we'll use to setup the man:git-worktree[1].
+
All of these will be passed through as-is, except we'll add a thin
wrapper of 'cd <run-dir> && ...'.

-L, --parameter-list::
	Passed through as-is, except as a sanity check we'll die if
	you don't create a '-L rev ...' option. Our '--setup' option
	requires it to work.

-n, --command-name::
	You're not allowed to supply this anymore, as we'll need it to
	relabel our ugly generated 'cd <x> && ...' command name.

CONFIGURATION
-------------

This command can be configured through man:git-config[1], all the
options are in the 'hyperfine.*' namespace:

MANDATORY CONFIGURATION
~~~~~~~~~~~~~~~~~~~~~~~

hyperfine.run-dir::
	Mandatory configuration which determines where to place the
	man:git-worktree[1] trees we create for resting the '{rev}'
	arguments.
+
Environment variables are supported, they're not understood by
man:git-config[1], but we'll shell 'eval()' this value.
+
A good setting would be:
+
----
[hyperfine]
run-dir = $XDG_RUNTIME_DIR/git-perf
----

hyperfine.xargs-options::
	Options given to man:xargs[1] when the `--ghf-worktree-xargs'
	option is used. Set this to '-r' to use the GNU extension to
	ignore empty input. Otherwise supplying e.g. "git worktree
	remove" will show an annoying usage error from
	link:git-worktree[1] if there's no worktrees to operate on.

HOOK CONFIGURATION[HOOKCFG]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This will affect all git-hyperfine invocations, but you can use the
path includes in 'git config' to limit them, or e.g. set them
per-repository.

All of the hooks are arbitrary shell commands (interpolated into the
relevant man:hyperfine[1] options).

If they're defined they'll be run even if you didn't provide the
relevant optional '--setup', '--prepare', '<command>' or '--cleanup'
option.

In the case of '--setup' this wouldn't matter either way, since
'git-hyperfine' always provides its own '--setup' template, but it
might be unexpected in other cases.

This is so that e.g. the '--cleanup' hook can be (ab)used to
optionally cleanup 'git-hyperfine's own litter, you can even (ab)use
it omit the '<command>' name and run the ook instead. In that case the
title of the command will be the value defined in the hook
configuration.

hyperfine.hook.setup::
	A hook for the '--setup' phase.
+
I use the 'setup' hook to copy a 'config.mak' in-place with build
configuration for 'git.git', and 'prepare' can be used to always drop
FS caches.

hyperfine.hook.prepare::
	A hook for the '--prepare' phase.
+
Can be used to e.g. drop FS caches, as shown in the man:hyperfine[1]
README.md: https://github.com/sharkdp/hyperfine#basic-benchmark

hyperfine.hook.command::
	A hook for the '<command>' phase.
+
It's probably a bad idea to use this hook for anything, any use of it
will go into your benchmark results, but it's here for completeness
and flexibility.

hyperfine.hook.cleanup::
	A hook for the '<command>' cleanup phase.
+
The cleanup hook could be defined to e.g.:
+
----
git hyperfine --ghf-worktree-xargs remove
----

See the 'git-hyperfine-gitconfig.cfg' file in the 'git-hyperfine'
repository for configuration examples. That's also available at
https://gitlab.com/avar/git-hyperfine/-/blob/master/git-hyperfine-gitconfig.cfg
and
https://github.com/avar/git-hyperfine/blob/master/git-hyperfine-gitconfig.cfg

EXAMPLES[[XMPL]]
----------------

Test two revisions, and show that w we'll run in our worktree paths:

----
git hyperfine -L rev HEAD,HEAD~ -r 2 -s 'echo setup: $(pwd)' 'echo run: $(pwd)' -c 'echo cleanup: $(pwd)' -p 'echo prepare: $(pwd)' --show-output
----

Show when all of our hooks and commands would be run relative to one
another:

----
git -c hyperfine.hook.setup='echo HOOK setup' \
    -c hyperfine.hook.prepare='echo HOOK prepare' \
    -c hyperfine.hook.command='echo HOOK command' \
     -c hyperfine.hook.cleanup='echo HOOK cleanup' \
     hyperfine --show-output -r 2 -L rev HEAD~1,HEAD~0 \
     -s 'echo setup' \
     -p 'echo prepare' \
     -c 'echo cleanup' \
     'git -P log --pretty=reference -1'
----

DEPENDENCIES
------------

POSIX shell script. See <<COMPAT,COMPATIBILITY>> below.

To install documentation you'll need man:asciidoctor[1].

COMPATIBILITY[[COMPAT]]
-----------------------

'git-hyperfine' is written in in POSIX shellscript. It should be
compatible with Linux systems, BSDs, OSX, Solaris (not its /bin/sh
though), AIX, HP/UX etc. etc. Any incompatibility is a (probably small
and easily fixed) bug.

INSTALLATION
------------

"git clone" the repository and add it to your '$PATH' for a quick
try-out (or don't add it to '$PATH' and provide the full path name).

For a proper installation there's an old-school GNU make 'Makefile' in
the top-level, to build and see what we'd install do:

----
make install INSTALL='@echo install'
----

And to install it for real drop the 'INSTALL' parameter, e.g.:

----
sudo make install prefix=/usr
----

To build and install documentation add 'install-man' to that (only the
latter target is needed). You can provide 'ASCIIDOCTOR' to be the path
to your 'asciidoctor' (or compatible) program.

----
make man
sudo make install-man prefix=/usr
----

HIPSTER INSTALLATION[[HIPSTER]]
-------------------------------

Like piping random code from the Internetz to man:sudo[1]? This one's
for you:

----
sudo bash -c "make prefix=$HOME/local HIPSTER=Y install install-man -f<(curl -s -o - https://gitlab.com/avar/git-hyperfine/-/raw/master/Makefile)"
----

It doesn't even require man:bash[1] (or man:sudo[1]), but if you like
to live dangerously.

AUTHOR
------

Ævar Arnfjörð Bjarmason

LICENSE
-------

'git-hyperfine' is triple-licensed under GPL v2.0 or later, MIT
License, and Apache License 2.0 or later.

I.e. a more than generous combination of the licenses of upstream
utilities it uses and extends. See
https://github.com/sharkdp/hyperfine/#license and
https://github.com/git/git/blob/master/COPYING

SEE ALSO
--------

man:hyperfine[1]

BUGS
----

If man:hyperfine[1] introduces a new option 'git-hyperfine' currently
needs to be updated to know how to pass it through (its option usage
is somewhat irregular).

<<HIPSTER,HIPSTER INSTALLATION>> mode will cache the downloaded
program in the current working directory by virtue of being a
functioning 'Makefile' under the hood. It should probably download a
1GB tarball from somewhere instead to provide the full experience.
EOF
	exit 0
fi

## Configuration
cfg_run_dir=
cfg_xargs_opts=
cfg_hook_setup=
cfg_hook_prepare=
cfg_hook_command=
cfg_hook_cleanup=
parse_hyperfine_config () {
	# I really should add an --output=sh or something to
	# git-config(1).
	git config ${BASH_VERSION:+-z }--get-regexp '^hyperfine\.' |
	while read  ${BASH_VERSION:+-d $'\0' }k v
	do
		case "$k" in
		hyperfine.run-dir)
			echo cfg_run_dir="\"$v\""
			;;
		hyperfine.xargs-options)
			echo cfg_xargs_opts="\"$v\""
			;;
		hyperfine.hook.setup)
			echo cfg_hook_setup="\"$v\""
			;;
		hyperfine.hook.prepare)
			echo cfg_hook_prepare="\"$v\""
			;;
		hyperfine.hook.command)
			echo cfg_hook_command="\"$v\""
			;;
		hyperfine.hook.cleanup)
			echo cfg_hook_cleanup="\"$v\""
			;;
		hyperfine.*)
			echo "git-hyperfine: unknown option '$k'='$v' in config" >&2
			;;
		esac
	done
}	

cfg=$(parse_hyperfine_config)
debug "config to eval" $cfg
eval "$cfg"

## We need to resolve the {rev} from the originating repository. Not
## our {run_dir}.
git_dir=$(git rev-parse --absolute-git-dir)

## --ghf-worktree-list
worktree_list () {
	# I can't remember how to do this with just sed(1), but you
	# can.
	git worktree list --porcelain --porcelain |
	grep "^worktree $cfg_run_dir" |
	sed 's/^worktree //'
}
if test -n "$worktree_list"
then
	worktree_list
	exit $?
fi

## --ghf-worktree-xargs
if test -n "$worktree_xargs"
then
	echo dry=$dry_run 
	worktree_list | xargs -n 1${cfg_xargs_opts:+ $cfg_xargs_opts} ${dry_run:+hello }$@
	exit $?
fi

## --version output specific to git-hyperfine
if test -n "$version"
then
	echo git-hyperfine version whatever
	exit 0
fi

## Options sanity check
if test -z "$saw_rev"
then
	echo "git-hyperfine needs a -L rev <rev>..., e.g. -L rev HEAD~1,HEAD~0" >&2
	exit 1
fi

if test -n "$command_name"
then
	echo "$git-hyperfine can't take your -n|--command-name $command_name. It needs it" >&2
	exit 1
fi

## Templates for the command
## We're chain-invoking ourselves to get --setup etc. output below,
## this is to avoid some f the painful shell escaping
ghf_setup_template() {
	test -n "$debug_trace" && echo "set -x &&"
	cat <<-EOF |
	git_rev="\$(git -C "{git_dir}" rev-parse {rev})" &&
	if ! test -d "{run_dir}/{rev}"
	then
		git worktree add "{run_dir}/{rev}" "{rev}";
	fi &&
	git -C "{run_dir}/{rev}" reset --quiet --hard \$git_rev &&
	cd "{run_dir}/{rev}" ${trace:+ &&}
	EOF
	sed \
	    -e "s!{run_dir}!$cfg_run_dir!g" \
	    -e "s!{git_dir}!$git_dir!g" &&
	test -n "$trace" && echo "set -x"
}

## Debug utility
emit_dry_run() {
	printf "Would have invoke hyperfine(1) as:\n\n" >&2
	# TODO: Do something more clever
	printf "%s\n" $@
}

# We'll always provide --setup anyway, but we need these *_any for
# things that aren't implicit
prepare_any="$prepare$cfg_hook_prepare"
command_any="$command$cfg_hook_command"
cleanup_any="$prepare$cfg_hook_prepare"

command_title=$command
if test -n "$cfg_hook_command" && test -z "$command"
then
	command_title="$cfg_hook_command"
fi

${dry_run:+emit_dry_run} \
hyperfine $hyperfine_opt \
	--setup " \
		$(ghf_setup_template) \
		${cfg_hook_setup:+ && $cfg_hook_setup} \
		${setup:+ && $setup} \
	" \
	${prepare_any:+ --prepare "\
		${trace:+set -x;} \
		cd \"$cfg_run_dir/{rev}\" \
		${cfg_hook_prepare:+ && $cfg_hook_prepare} \
		${prepare:+ && $prepare} \
	"} \
	${cleanup_any:+ --cleanup "\
		${trace:+set -x;} \
		cd \"$cfg_run_dir/{rev}\" \
		${cfg_hook_cleanup:+ && $cfg_hook_cleanup} \
		${cleanup:+ && $cleanup} \
	"} \
	${command_any:+--command-name="$(tput setaf 6)$command_title$(tput sgr0)' in '$(tput setaf 6){rev}$(tput sgr0)"  \
	"\
		${trace:+set -x;} \
		cd \"$cfg_run_dir/{rev}\" \
		${cfg_hook_command:+ && $cfg_hook_command} \
		${command:+ && $command} \
	"}
